# Generated by Django 5.1.3 on 2024-11-14 08:26

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_course_public_id_alter_lesson_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
